version: 2

models:
  - name: inventory_dim
    description: "A transformed table that groups the inventory data by film and store, capturing the last update time."
    columns:
      - name: film_id
        description: "The ID of the film."
        tests:
          - not_null
      - name: store_id
        description: "The ID of the store."
        tests:
          - not_null
      - name: max_date
        description: "The latest update date for the inventory of each film in a store."
        tests:
          - not_null
