version: 2

models:
  - name: sales_inventory_distance_report
    description: "Summary of records by Commute Distance"
    columns:
      - name: Customer Key
        description: "Customer Id"
      - name: record_count
        description: "The number of records for each Customer Id."
        tests:
          - not_null
      - name: transformed_on
        description: "Data Transformation Time"
        tests:
          - not_null

          